//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumingWebService.SoapMine {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapMine.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Counting", ReplyAction="*")]
        int Counting(int firstNumber, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Counting", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CountingAsync(int firstNumber, int secondNumber);
        
        // CODEGEN: Generating message contract since element name getCalucationListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCalucationList", ReplyAction="*")]
        ConsumingWebService.SoapMine.getCalucationListResponse getCalucationList(ConsumingWebService.SoapMine.getCalucationListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCalucationList", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingWebService.SoapMine.getCalucationListResponse> getCalucationListAsync(ConsumingWebService.SoapMine.getCalucationListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCalucationListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCalucationList", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingWebService.SoapMine.getCalucationListRequestBody Body;
        
        public getCalucationListRequest() {
        }
        
        public getCalucationListRequest(ConsumingWebService.SoapMine.getCalucationListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getCalucationListRequestBody {
        
        public getCalucationListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCalucationListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCalucationListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingWebService.SoapMine.getCalucationListResponseBody Body;
        
        public getCalucationListResponse() {
        }
        
        public getCalucationListResponse(ConsumingWebService.SoapMine.getCalucationListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCalucationListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumingWebService.SoapMine.ArrayOfString getCalucationListResult;
        
        public getCalucationListResponseBody() {
        }
        
        public getCalucationListResponseBody(ConsumingWebService.SoapMine.ArrayOfString getCalucationListResult) {
            this.getCalucationListResult = getCalucationListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsumingWebService.SoapMine.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsumingWebService.SoapMine.WebService1Soap>, ConsumingWebService.SoapMine.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Counting(int firstNumber, int secondNumber) {
            return base.Channel.Counting(firstNumber, secondNumber);
        }
        
        public System.Threading.Tasks.Task<int> CountingAsync(int firstNumber, int secondNumber) {
            return base.Channel.CountingAsync(firstNumber, secondNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingWebService.SoapMine.getCalucationListResponse ConsumingWebService.SoapMine.WebService1Soap.getCalucationList(ConsumingWebService.SoapMine.getCalucationListRequest request) {
            return base.Channel.getCalucationList(request);
        }
        
        public ConsumingWebService.SoapMine.ArrayOfString getCalucationList() {
            ConsumingWebService.SoapMine.getCalucationListRequest inValue = new ConsumingWebService.SoapMine.getCalucationListRequest();
            inValue.Body = new ConsumingWebService.SoapMine.getCalucationListRequestBody();
            ConsumingWebService.SoapMine.getCalucationListResponse retVal = ((ConsumingWebService.SoapMine.WebService1Soap)(this)).getCalucationList(inValue);
            return retVal.Body.getCalucationListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingWebService.SoapMine.getCalucationListResponse> ConsumingWebService.SoapMine.WebService1Soap.getCalucationListAsync(ConsumingWebService.SoapMine.getCalucationListRequest request) {
            return base.Channel.getCalucationListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingWebService.SoapMine.getCalucationListResponse> getCalucationListAsync() {
            ConsumingWebService.SoapMine.getCalucationListRequest inValue = new ConsumingWebService.SoapMine.getCalucationListRequest();
            inValue.Body = new ConsumingWebService.SoapMine.getCalucationListRequestBody();
            return ((ConsumingWebService.SoapMine.WebService1Soap)(this)).getCalucationListAsync(inValue);
        }
    }
}
